apiVersion: v1
kind: Service
metadata:
  name: bgd-re
  namespace: bgd-re
  labels:
    app: bgd-re
spec:
  selector:
    app: bgd-re
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080