apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgd-re
  namespace: bgd-re
  labels:
    app: bgd-re
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd-re
  template:
    metadata:
      labels:
        app: bgd-re
      creationTimestamp: null
    spec:
      containers:
        - name: bgd-re
          image: quay.io/rhdevelopers/bgd:1.0.0
          env:
            - name: COLOR
              value: "blue"